"""Generated by bh-migrate-streamsets (target_format=spark-plain).
Source StreamSets pipeline: BHPOSGRESJOINKAFKA2e811645-0a11-455a-99c5-cca331356004 (BH-POSGRES-JOIN-KAFKA)
Secrets: set *_env variables from connections.yml before running.
JDBC/S3/Kafka jars: configured via spark.jars.packages (see main() builder).
Testable: call run_pipeline(spark, conns, fixtures={...}, sinks={}) with mock rows.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

"""Standalone spark-plain runtime helpers (also inlined into generated main.py).

Kept free of bh_migrate_streamsets imports so published pipelines stay runnable
without installing the migrate provider package.
"""


import importlib
import json
import os
import subprocess
import sys
from pathlib import Path

def _ensure_dependencies():
    """Auto-install required Python packages (boto3, pyyaml) if missing."""
    required = {
        "yaml": "pyyaml",
        "boto3": "boto3",
    }
    for mod_name, pkg_name in required.items():
        try:
            importlib.import_module(mod_name)
        except ImportError:
            try:
                subprocess.check_call(
                    [sys.executable, "-m", "pip", "install", pkg_name],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            except Exception:
                pass


_ensure_dependencies()


def _env(name, default=None):
    if not name:
        return default
    return os.environ.get(str(name), default)


def _rename_column_ci(df, src, dst):
    """Rename src→dst with case-insensitive source match; no-op if src missing.

    When both names are present the destination is already populated (readers
    that project ``src AS dst`` make this rename a no-op), so the redundant
    source is dropped rather than allowed to overwrite the destination.
    """
    if src == dst:
        return df
    cols = list(df.columns)
    resolved = src if src in cols else next((c for c in cols if str(c).lower() == str(src).lower()), None)
    if resolved is None:
        return df
    if dst in cols and dst != resolved:
        return df.drop(resolved)
    return df.withColumnRenamed(resolved, dst)


def _normalize_secret_payload(data):
    """Flatten config blocks and normalize common Kafka / JDBC secret key aliases.

    Nested ``config`` is flattened away. Non-empty top-level keys override
    ``config`` (same precedence as ``{**cfg, **data}`` for real values). Empty
    or null top-level values do not wipe a nested ``config`` value.
    """
    if not isinstance(data, dict):
        return {}
    cfg = data.get("config")
    merged = dict(cfg) if isinstance(cfg, dict) else {}
    for key, value in data.items():
        if key == "config":
            continue
        if value not in (None, ""):
            merged[key] = value
    alias_groups = {
        "ssl_truststore_password": (
            "truststorePassword",
            "truststore_password",
            "sslTruststorePassword",
        ),
        "ssl_keystore_password": (
            "keystorePassword",
            "keystore_password",
            "sslKeystorePassword",
        ),
        "ssl_key_password": ("keyPassword", "key_password", "sslKeyPassword"),
        "bootstrap_servers": ("bootstrap.servers", "metadataBrokerList"),
        "security_protocol": ("securityProtocol", "security_protocol"),
        "sasl_mechanism": ("saslMechanism", "sasl_mechanism"),
        "sasl_username": ("username", "user"),
        "sasl_password": ("password", "pass"),
    }
    for canonical, aliases in alias_groups.items():
        if merged.get(canonical) not in (None, ""):
            continue
        for alt in aliases:
            if merged.get(alt) not in (None, ""):
                merged[canonical] = merged[alt]
                break
    return merged


_SECRET_CACHE = {}


def _secret_payload(value):
    if not isinstance(value, str) or not value.strip():
        return {}
    text = value.strip()
    if text.startswith("{"):
        try:
            data = json.loads(text)
        except Exception:
            data = None
        if isinstance(data, dict):
            return _normalize_secret_payload(data)
    return {"password": text, "aws_secret_access_key": text}


def _secret_name_candidates(secret_name):
    """Vault lookup names for a secret ref.

    Catalog stores scoped refs such as ``<kv-scope>/<secret-name>`` while the
    vault only holds the trailing segment, so the tail is tried first.
    """
    raw = str(secret_name or "").strip()
    if not raw:
        return []
    candidates = []
    for cand in (raw.rsplit("/", 1)[-1].strip(), raw, raw.replace("/", "-")):
        if cand and cand not in candidates:
            candidates.append(cand)
    return candidates


def _azure_secret_client():
    vault_url = (
        os.environ.get("AZURE_VAULT_URL")
        or os.environ.get("AZURE_KEYVAULT_URL")
        or os.environ.get("KEY_VAULT_URL")
    )
    if not vault_url:
        return None
    from azure.keyvault.secrets import SecretClient

    tenant = os.environ.get("AZURE_TENANT_ID")
    client_id = os.environ.get("AZURE_CLIENT_ID")
    client_secret = os.environ.get("AZURE_CLIENT_SECRET")
    if tenant and client_id and client_secret:
        from azure.identity import ClientSecretCredential

        credential = ClientSecretCredential(tenant, client_id, client_secret)
    else:
        from azure.identity import DefaultAzureCredential

        credential = DefaultAzureCredential()
    return SecretClient(vault_url=vault_url, credential=credential)


def _fetch_secret(conn):
    """Retrieve secret credentials dynamically using secret_name from Secrets Manager / KeyVault."""
    if not isinstance(conn, dict):
        return {}
    secret_name = str(conn.get("secret_name") or "").strip()
    if not secret_name:
        return {}
    if secret_name in _SECRET_CACHE:
        return _SECRET_CACHE[secret_name]

    candidates = _secret_name_candidates(secret_name)
    resolved = {}

    if str(os.environ.get("SECRET_MANAGER_PROVIDER") or "").lower() != "azure":
        try:
            import boto3
            region = conn.get("region_name") or conn.get("region") or os.environ.get("AWS_DEFAULT_REGION", "us-east-1")
            client = boto3.client("secretsmanager", region_name=region)
            for candidate in candidates:
                try:
                    resp = client.get_secret_value(SecretId=candidate)
                except Exception:
                    continue
                if "SecretString" in resp:
                    resolved = _secret_payload(resp["SecretString"])
                    if resolved:
                        break
        except Exception:
            pass

    if not resolved:
        try:
            client = _azure_secret_client()
            if client is not None:
                for candidate in candidates:
                    try:
                        sec = client.get_secret(candidate)
                    except Exception:
                        continue
                    if sec and sec.value:
                        resolved = _secret_payload(sec.value)
                        if resolved:
                            break
        except Exception:
            pass

    _SECRET_CACHE[secret_name] = resolved
    return resolved


def _jdbc_driver(connection_type):
    return {
        "PostgreSQL": "org.postgresql.Driver",
        "Oracle": "oracle.jdbc.OracleDriver",
        "MySQL": "com.mysql.cj.jdbc.Driver",
        "MsSQL": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        "Snowflake": "net.snowflake.client.jdbc.SnowflakeDriver",
    }.get(str(connection_type or ""), "org.postgresql.Driver")


def _local_path(prefix, file_name):
    prefix = (prefix or "").rstrip("/")
    file_name = (file_name or "").lstrip("/")
    if not prefix:
        return file_name or "."
    if not file_name:
        return prefix
    return f"{prefix}/{file_name}"


def _s3_path(conn, file_name, prefix=""):
    sec = _fetch_secret(conn)
    bucket = sec.get("bucket") or conn.get("bucket") or ""
    base = (sec.get("file_path_prefix") or sec.get("prefix") or conn.get("file_path_prefix") or prefix or "").strip("/")
    name = (file_name or "").lstrip("/")
    parts = [p for p in (base, name) if p]
    key = "/".join(parts)
    if bucket:
        return f"s3a://{bucket}/{key}" if key else f"s3a://{bucket}"
    return key or "."


def _configure_s3(spark, conn):
    conf = spark.sparkContext._jsc.hadoopConfiguration()
    secrets = _fetch_secret(conn)
    # Catalog live enrich inlines aws_* on conn; prefer those when SM/KV is unreachable.
    key = (
        _env(conn.get("aws_access_key_id_env"))
        or secrets.get("aws_access_key_id")
        or secrets.get("access_key")
        or conn.get("aws_access_key_id")
        or conn.get("access_key")
        or os.environ.get("AWS_ACCESS_KEY_ID")
    )
    secret = (
        _env(conn.get("aws_secret_access_key_env"))
        or secrets.get("aws_secret_access_key")
        or secrets.get("secret_key")
        or conn.get("aws_secret_access_key")
        or conn.get("secret_key")
        or os.environ.get("AWS_SECRET_ACCESS_KEY")
    )
    token = (
        os.environ.get("AWS_SESSION_TOKEN")
        or secrets.get("aws_session_token")
        or conn.get("aws_session_token")
    )
    if key and secret:
        conf.set("fs.s3a.access.key", key)
        conf.set("fs.s3a.secret.key", secret)
        if token:
            conf.set("fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider")
            conf.set("fs.s3a.session.token", token)
        else:
            conf.set("fs.s3a.aws.credentials.provider", "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider")
    elif key:
        conf.set("fs.s3a.access.key", key)
    elif secret:
        conf.set("fs.s3a.secret.key", secret)
    else:
        conf.set("fs.s3a.aws.credentials.provider", "com.amazonaws.auth.DefaultAWSCredentialsProviderChain")
    region = conn.get("region_name") or conn.get("region") or os.environ.get("AWS_DEFAULT_REGION", "us-east-1")
    if region:
        conf.set("fs.s3a.endpoint.region", str(region))
    endpoint = conn.get("endpoint_url")
    if endpoint:
        conf.set("fs.s3a.endpoint", str(endpoint))


def _load_connections(path):
    text = Path(path).read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore
        data = yaml.safe_load(text) or {}
    except Exception:
        # Minimal YAML subset fallback (key: / nested scalars) via json if converted.
        data = {}
        current = None
        for raw in text.splitlines():
            line = raw.split("#", 1)[0].rstrip()
            if not line.strip():
                continue
            if not line.startswith(" ") and line.endswith(":"):
                current = line[:-1].strip().strip('"').strip("'")
                data[current] = {}
                continue
            if current is None or ":" not in line:
                continue
            k, v = line.strip().split(":", 1)
            v = v.strip()
            if v in {"true", "false"}:
                parsed = v == "true"
            else:
                try:
                    parsed = json.loads(v)
                except Exception:
                    parsed = v.strip('"').strip("'")
            data[current][k.strip()] = parsed
    if not isinstance(data, dict):
        return {}
    return data


def _run_bh_scala(spark, *, name, user_code, inputs, skip_empty_batches=True):
    """Run BH Scala user_code (inputs(i) / output) via JVM IMain — same contract as TTU.

    Prefer TTU ``Scala`` when installed; otherwise use an embedded IMain harness so
    standalone spark-plain projects stay runnable without bh-transformation-utils.
    Custom classes (e.g. BankRiskEngine) require JARs on the Spark session classpath.
    """
    input_dfs = list(inputs or [])
    if not input_dfs:
        raise ValueError(f"Scala stage {name!r} requires at least one input DataFrame")
    if skip_empty_batches and all(df.rdd.isEmpty() for df in input_dfs):
        return input_dfs[0]

    # TTU path (K8s / local TTU image).
    try:
        from bh_transformation_utils.engines.batch.pyspark.transformations.scala import (
            Scala as _BhScala,
        )

        stage = _BhScala(
            name=name,
            user_code=user_code,
            skip_empty_batches=False,  # empty-batch already handled above
        )
        out = stage.apply(
            [{"name": f"in_{i}", "data": df} for i, df in enumerate(input_dfs)]
        )
        return out[0]["data"]
    except ImportError:
        pass

    import uuid as _uuid

    jvm = spark._jvm
    run_id = _uuid.uuid4().hex[:12]
    in_views = []
    stale_views = []
    try:
        for i, df in enumerate(input_dfs):
            view = f"__bh_scala_in_{run_id}_{i}"
            df.createOrReplaceTempView(view)
            in_views.append(view)
        inputs_expr = ", ".join(f'spark.table("{v}")' for v in in_views)
        harness = (
            "val spark = org.apache.spark.sql.SparkSession.getActiveSession.get\\n"
            f"val inputs = Array({inputs_expr})\\n"
            "var output: org.apache.spark.sql.DataFrame = _\\n"
            f"{str(user_code).rstrip()}\\n"
        )
        settings = jvm.scala.tools.nsc.Settings()
        settings.usejavacp().tryToSetFromPropertyValue("true")
        string_writer = jvm.java.io.StringWriter()
        print_writer = jvm.java.io.PrintWriter(string_writer, True)
        imain = jvm.scala.tools.nsc.interpreter.IMain(settings, print_writer)
        result = imain.interpret(harness)
        result_name = result.toString()
        compiler_log = string_writer.toString()
        success = result_name == "Success"
        if not success:
            try:
                success_cls = jvm.scala.tools.nsc.interpreter.Results.Success()
                success = result.equals(success_cls) or result == success_cls
            except Exception:
                pass
        if not success:
            raise RuntimeError(
                f"Scala compilation/execution failed (status={result_name}).\\n"
                f"Compiler output:\\n{compiler_log}"
            )
        terms = imain.definedTerms()
        iterator = terms.iterator()
        jvm_df = None
        while iterator.hasNext():
            term = iterator.next()
            tname = term.toString()
            if tname == "output" or tname.startswith("result"):
                val_opt = imain.valueOfTerm(tname)
                if val_opt.isDefined():
                    cand = val_opt.get()
                    if cand is not None:
                        cls_name = cand.getClass().getName()
                        if "Dataset" in cls_name or "DataFrame" in cls_name:
                            jvm_df = cand
                            if tname == "output":
                                break
        if jvm_df is None:
            raise RuntimeError(
                "Scala user_code must assign output or define variables starting with 'result'"
            )
        out_view = f"__bh_scala_out_{run_id}"
        jvm_df.createOrReplaceTempView(out_view)
        out_df = spark.table(out_view)
        # Cut lineage while the input views still exist, then the views are safe to
        # delete. Returning a lazy plan instead lets a later action re-resolve those
        # view names against a mutated catalog and read another pipeline's data.
        try:
            out_df = out_df.localCheckpoint(eager=True)
            stale_views.extend(in_views)
            stale_views.append(out_view)
        except Exception:
            # Lineage still live: keep the views. They are run-scoped names, so
            # leaking them is far cheaper than resolving against the wrong plan.
            out_df.cache()
            out_df.count()
        return out_df
    finally:
        for view in stale_views:
            try:
                spark.catalog.dropTempView(view)
            except Exception:
                pass


def run_pipeline(spark, conns, *, fixtures=None, sinks=None):
    """Run the migrated pipeline.

    fixtures: optional {reader_stage_name: [row_dict, ...]} to skip live I/O.
    sinks: optional dict; when provided, writers store DataFrames here instead of I/O.
    """
    fixtures = fixtures or {}

    if fixtures and "PostgreSQL_JDBC_Table_1" in fixtures:
        PostgreSQL_JDBC_Table_1 = spark.createDataFrame(fixtures["PostgreSQL_JDBC_Table_1"])
    else:
        # Reader PostgreSQL_JDBC_Table_1 (JDBC / PostgreSQL)
        _conn = conns["migrate_postgres"]
        _secrets = _fetch_secret(_conn)
        _url = "jdbc:postgresql://{h}:{p}/{db}".format(h=_secrets.get("host") or conns["migrate_postgres"].get("host") or "localhost", p=_secrets.get("port") or conns["migrate_postgres"].get("port") or 5432, db=_secrets.get("database") or _secrets.get("dbname") or conns["migrate_postgres"].get("database") or "postgres")
        _props = { "user": _secrets.get("username") or _secrets.get("user") or _env(_conn.get("username_env")) or _conn.get("username", "postgres"), "password": _secrets.get("password") or _secrets.get("pass") or _env(_conn.get("password_env")) or _conn.get("password", ""), "driver": _jdbc_driver(_conn.get("connection_type")), }
        PostgreSQL_JDBC_Table_1 = spark.read.jdbc(url=_url, table="bank_test.bank_tenant", properties=_props)

    if fixtures and "PostgreSQL_JDBC_Table_1_2" in fixtures:
        PostgreSQL_JDBC_Table_1_2 = spark.createDataFrame(fixtures["PostgreSQL_JDBC_Table_1_2"])
    else:
        # Reader PostgreSQL_JDBC_Table_1_2 (JDBC / PostgreSQL)
        _conn = conns["migrate_postgres"]
        _secrets = _fetch_secret(_conn)
        _url = "jdbc:postgresql://{h}:{p}/{db}".format(h=_secrets.get("host") or conns["migrate_postgres"].get("host") or "localhost", p=_secrets.get("port") or conns["migrate_postgres"].get("port") or 5432, db=_secrets.get("database") or _secrets.get("dbname") or conns["migrate_postgres"].get("database") or "postgres")
        _props = { "user": _secrets.get("username") or _secrets.get("user") or _env(_conn.get("username_env")) or _conn.get("username", "postgres"), "password": _secrets.get("password") or _secrets.get("pass") or _env(_conn.get("password_env")) or _conn.get("password", ""), "driver": _jdbc_driver(_conn.get("connection_type")), }
        PostgreSQL_JDBC_Table_1_2 = spark.read.jdbc(url=_url, table="bank_test.customer", properties=_props)

    # Python Aggregate_1
    _ns = {
        "PostgreSQL_JDBC_Table_1_2": PostgreSQL_JDBC_Table_1_2,
        "PostgreSQL_JDBC_Table_1_2": PostgreSQL_JDBC_Table_1_2,
        'spark': spark,
        'F': F,
    }
    exec("# FUTURE_SCOPE: StreamSets aggregation stage 'Aggregate 1' (com_streamsets_pipeline_spark_transform_aggr_AggregateDTransform)\n# Orchestration / side-effect \u2014 not executed as a row transform.\n\"\"\"\n{\n  \"cache\": false,\n  \"conf.aggrTypeAndFields\": [\n    {\n      \"aggregateType\": \"COUNT\",\n      \"outputField\": \"customer_id\"\n    }\n  ],\n  \"conf.groupByFields\": [\n    \"tenant_id\"\n  ]\n}\n\"\"\"\nresult = PostgreSQL_JDBC_Table_1_2\n", _ns)
    Aggregate_1 = _ns.get('result') or _ns.get("Aggregate_1") or PostgreSQL_JDBC_Table_1_2

    # Joiner Join_1
    Join_1 = PostgreSQL_JDBC_Table_1.alias("PostgreSQL_JDBC_Table_1")

    if sinks is not None:
        sinks["Kafka_1"] = Join_1
    else:
        # Writer Kafka_1 (Kafka)
        _conn = conns["migrate_kafka"]
        _secrets = _fetch_secret(_conn)
        _bootstrap = _secrets.get('bootstrap_servers') or _conn.get('bootstrap_servers') or ''
        _kdf = Join_1.selectExpr('to_json(struct(*)) as value')
        _kr = (
        _kdf.write.format('kafka')
        .option('kafka.bootstrap.servers', _bootstrap)
        .option('topic', "test-join")
    )
        _secrets = _fetch_secret(_conn)
        _sec = str(_secrets.get('security_protocol') or _conn.get('security_protocol') or '').strip().upper()
        if _sec and _sec != 'PLAINTEXT':
            _kr = _kr.option('kafka.security.protocol', _sec)
        _ca_pem = _secrets.get('ssl_ca_pem') or _conn.get('ssl_ca_pem')
        if not _ca_pem and _sec in ('SSL', 'SASL_SSL') and not os.path.exists(str(_secrets.get('ssl_truststore_location') or _conn.get('ssl_truststore_location') or '')):
            try:
                import ssl
                _srv = str(_secrets.get('bootstrap_servers') or _conn.get('bootstrap_servers') or '').split(',')[0].strip()
                if ':' in _srv:
                    _h, _p = _srv.split(':', 1)
                    _ca_pem = ssl.get_server_certificate((_h, int(_p)))
            except Exception:
                pass
        if _ca_pem:
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', delete=False, prefix='kafka_ca_', suffix='.pem', encoding='utf-8') as _tmp_ca:
                _tmp_ca.write(str(_ca_pem).strip() + '\n')
                _kr = _kr.option('kafka.ssl.truststore.location', _tmp_ca.name)
                _kr = _kr.option('kafka.ssl.truststore.type', 'PEM')
        else:
            _ts_loc = _secrets.get('ssl_truststore_location') or _conn.get('ssl_truststore_location')
            if _ts_loc and os.path.exists(str(_ts_loc)):
                _kr = _kr.option('kafka.ssl.truststore.location', str(_ts_loc))
                _ts_pass = (_env(_conn.get('ssl_truststore_password_env')) or _secrets.get('ssl_truststore_password') or _conn.get('ssl_truststore_password') or _secrets.get('truststorePassword') or _secrets.get('truststore_password'))
                if _ts_pass:
                    _kr = _kr.option('kafka.ssl.truststore.password', _ts_pass)
        _cert_pem = _secrets.get('ssl_cert_pem') or _conn.get('ssl_cert_pem')
        _key_pem = _secrets.get('ssl_key_pem') or _conn.get('ssl_key_pem')
        if _cert_pem and _key_pem:
            import tempfile
            with tempfile.NamedTemporaryFile(mode='w', delete=False, prefix='kafka_ks_', suffix='.pem', encoding='utf-8') as _tmp_ks:
                _tmp_ks.write(str(_cert_pem).strip() + '\n' + str(_key_pem).strip() + '\n')
                _kr = _kr.option('kafka.ssl.keystore.location', _tmp_ks.name)
                _kr = _kr.option('kafka.ssl.keystore.type', 'PEM')
                _key_pass = (_env(_conn.get('ssl_key_password_env')) or _secrets.get('ssl_key_password') or _conn.get('ssl_key_password'))
                if _key_pass:
                    _kr = _kr.option('kafka.ssl.key.password', _key_pass)
        else:
            _ks_loc = _secrets.get('ssl_keystore_location') or _conn.get('ssl_keystore_location')
            _ks_pass = (_env(_conn.get('ssl_keystore_password_env')) or _secrets.get('ssl_keystore_password') or _conn.get('ssl_keystore_password') or _secrets.get('keystorePassword') or _secrets.get('keystore_password') or _secrets.get('ssl_key_password') or _secrets.get('keyPassword'))
            if _ks_loc and os.path.exists(str(_ks_loc)) and _ks_pass:
                _kr = _kr.option('kafka.ssl.keystore.location', str(_ks_loc))
                if str(_ks_loc).lower().endswith(('.p12', '.pfx')):
                    _kr = _kr.option('kafka.ssl.keystore.type', 'PKCS12')
                _kr = _kr.option('kafka.ssl.keystore.password', _ks_pass)
                _key_pass = (_env(_conn.get('ssl_key_password_env')) or _secrets.get('ssl_key_password') or _conn.get('ssl_key_password') or _secrets.get('keyPassword'))
                if _key_pass:
                    _kr = _kr.option('kafka.ssl.key.password', _key_pass)
        _sasl_user = _env(_conn.get('sasl_username_env')) or _secrets.get('sasl_username') or _conn.get('sasl_username') or _secrets.get('username')
        _sasl_pass = _env(_conn.get('sasl_password_env')) or _secrets.get('sasl_password') or _conn.get('sasl_password') or _secrets.get('password')
        if _sasl_user:
            _kr = _kr.option(
                "kafka.security.protocol", _secrets.get("security_protocol") or _conn.get("security_protocol") or "SASL_SSL")
            _kr = _kr.option(
                "kafka.sasl.mechanism", _secrets.get("sasl_mechanism") or _conn.get("sasl_mechanism") or "PLAIN")
            _jaas = ('org.apache.kafka.common.security.plain.PlainLoginModule required '
         'username="' + str(_sasl_user).replace('\\', '\\\\').replace('"', '\\"') + '" '
         'password="' + str(_sasl_pass or '').replace('\\', '\\\\').replace('"', '\\"') + '";')
            _kr = _kr.option("kafka.sasl.jaas.config", _jaas)
        _sr_url = _secrets.get('schema_registry_url') or _conn.get('schema_registry_url')
        if _sr_url:
            try:
                import urllib.request
                from urllib.parse import quote
                _sr_headers = {'Content-Type': 'application/vnd.schemaregistry.v1+json', 'Accept': 'application/vnd.schemaregistry.v1+json, application/json'}
                _sr_client_id = _secrets.get('schema_registry_client_id') or _conn.get('schema_registry_client_id')
                if _sr_client_id:
                    _t_id = _secrets.get('schema_registry_tenant_id') or _conn.get('schema_registry_tenant_id')
                    _c_sec = _secrets.get('schema_registry_client_secret') or _conn.get('schema_registry_client_secret')
                    _scope = _secrets.get('schema_registry_scope') or f'{_sr_client_id}/.default'
                    _t_req = urllib.request.Request(
                        f'https://login.microsoftonline.com/{_t_id}/oauth2/v2.0/token',
                        data=f'grant_type=client_credentials&client_id={_sr_client_id}&client_secret={quote(_c_sec or "")}&scope={quote(_scope or "")}'.encode('utf-8'),
                        headers={'Content-Type': 'application/x-www-form-urlencoded'}
                    )
                    with urllib.request.urlopen(_t_req) as _t_resp:
                        _tok = json.loads(_t_resp.read().decode('utf-8')).get('access_token')
                        if _tok:
                            _sr_headers['Authorization'] = f'Bearer {_tok}'
                _fields = [{'name': c, 'type': 'string'} for c in Join_1.columns]
                _avro_json = json.dumps({'type': 'record', 'name': "test-join", 'fields': _fields})
                _post_body = json.dumps({'schema': _avro_json, 'schemaType': 'AVRO'}).encode('utf-8')
                _sr_req = urllib.request.Request(f'{_sr_url.rstrip("/")}/subjects/{quote("test-join")}-value/versions', data=_post_body, headers=_sr_headers, method='POST')
                with urllib.request.urlopen(_sr_req) as _sr_resp:
                    pass
            except Exception:
                pass
        _kr.save()


def main():
    builder = SparkSession.builder.appName("bh_postgres_join_kafka")
    # JVM jars for JDBC / s3a / Kafka (TTU-aligned; must be set before getOrCreate)
    builder = builder.config('spark.jars.packages', "org.postgresql:postgresql:42.7.12,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.spark:spark-token-provider-kafka-0-10_2.12:3.5.1,org.apache.kafka:kafka-clients:3.4.1,org.apache.commons:commons-pool2:2.11.1")
    spark = builder.getOrCreate()
    conns = _load_connections(Path(__file__).parent / 'connections.yml')
    run_pipeline(spark, conns)
    spark.stop()


if __name__ == "__main__":
    main()
